# Generated by Django 4.2 on 2023-04-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_product', models.CharField(max_length=100)),
                ('user_product_quantity', models.IntegerField()),
                ('total_for_product', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
