# Generated by Django 4.2 on 2023-05-20 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_usercart_delete_shoppingcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_product_quantity', models.IntegerField()),
                ('total_for_product', models.FloatField()),
                ('user_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.product')),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='reg_date',
            new_name='reg_data',
        ),
        migrations.DeleteModel(
            name='UserCart',
        ),
    ]
